### ISSUE TITLE
ENH: ufunc implementation tracking list (up to 3D)

### ISSUE THREAD

**Issue by tylerjereddy** [kokkos/pykokkos#62]
Tracking issue for `ufunc` implementations (see: https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists ). 

- [ ] [numpy.add](https://numpy.org/doc/stable/reference/generated/numpy.add.html#numpy.add)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.subtract](https://numpy.org/doc/stable/reference/generated/numpy.subtract.html#numpy.subtract)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.multiply](https://numpy.org/doc/stable/reference/generated/numpy.multiply.html#numpy.multiply)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.divide](https://numpy.org/doc/stable/reference/generated/numpy.divide.html#numpy.divide)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.logaddexp](https://numpy.org/doc/stable/reference/generated/numpy.logaddexp.html#numpy.logaddexp)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.logaddexp2](https://numpy.org/doc/stable/reference/generated/numpy.logaddexp2.html#numpy.logaddexp2)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.true_divide](https://numpy.org/doc/stable/reference/generated/numpy.true_divide.html#numpy.true_divide)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.floor_divide](https://numpy.org/doc/stable/reference/generated/numpy.floor_divide.html#numpy.floor_divide)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.negative](https://numpy.org/doc/stable/reference/generated/numpy.negative.html#numpy.negative)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.positive](https://numpy.org/doc/stable/reference/generated/numpy.positive.html#numpy.positive)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.power](https://numpy.org/doc/stable/reference/generated/numpy.power.html#numpy.power)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.float_power](https://numpy.org/doc/stable/reference/generated/numpy.float_power.html#numpy.float_power)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.remainder](https://numpy.org/doc/stable/reference/generated/numpy.remainder.html#numpy.remainder)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.mod](https://numpy.org/doc/stable/reference/generated/numpy.mod.html#numpy.mod)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.fmod](https://numpy.org/doc/stable/reference/generated/numpy.fmod.html#numpy.fmod)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.divmod](https://numpy.org/doc/stable/reference/generated/numpy.divmod.html#numpy.divmod)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.absolute](https://numpy.org/doc/stable/reference/generated/numpy.absolute.html#numpy.absolute)
  - [ ] 1-D gh-46
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.fabs](https://numpy.org/doc/stable/reference/generated/numpy.fabs.html#numpy.fabs)
  - [ ] 1-D 
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.rint](https://numpy.org/doc/stable/reference/generated/numpy.rint.html#numpy.rint)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.sign](https://numpy.org/doc/stable/reference/generated/numpy.sign.html#numpy.sign)
  - [ ] 1-D gh-45
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.heaviside](https://numpy.org/doc/stable/reference/generated/numpy.heaviside.html#numpy.heaviside)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.conj](https://numpy.org/doc/stable/reference/generated/numpy.conj.html#numpy.conj)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.conjugate](https://numpy.org/doc/stable/reference/generated/numpy.conjugate.html#numpy.conjugate)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.exp](https://numpy.org/doc/stable/reference/generated/numpy.exp.html#numpy.exp)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.exp2](https://numpy.org/doc/stable/reference/generated/numpy.exp2.html#numpy.exp2)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.log](https://numpy.org/doc/stable/reference/generated/numpy.log.html#numpy.log)
  - [ ] 1-D gh-37
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.log2](https://numpy.org/doc/stable/reference/generated/numpy.log2.html#numpy.log2)
  - [ ] 1-D gh-37
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.log10](https://numpy.org/doc/stable/reference/generated/numpy.log10.html#numpy.log10)
  - [ ] 1-D gh-37
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.expm1](https://numpy.org/doc/stable/reference/generated/numpy.expm1.html#numpy.expm1)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.log1p](https://numpy.org/doc/stable/reference/generated/numpy.log1p.html#numpy.log1p)
  - [ ] 1-D gh-37
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html#numpy.sqrt)
  - [ ] 1-D gh-36
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.square](https://numpy.org/doc/stable/reference/generated/numpy.square.html#numpy.square)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.cbrt](https://numpy.org/doc/stable/reference/generated/numpy.cbrt.html#numpy.cbrt)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.reciprocal](https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html#numpy.reciprocal)
  - [x] 1-D gh-29
  - [x] 2-D gh-39
  - [ ] 3-D
- [ ] [numpy.gcd](https://numpy.org/doc/stable/reference/generated/numpy.gcd.html#numpy.gcd)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.lcm](https://numpy.org/doc/stable/reference/generated/numpy.lcm.html#numpy.lcm)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.sin](https://numpy.org/doc/stable/reference/generated/numpy.sin.html#numpy.sin)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.cos](https://numpy.org/doc/stable/reference/generated/numpy.cos.html#numpy.cos)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.tan](https://numpy.org/doc/stable/reference/generated/numpy.tan.html#numpy.tan)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.arcsin](https://numpy.org/doc/stable/reference/generated/numpy.arcsin.html#numpy.arcsin)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.arccos](https://numpy.org/doc/stable/reference/generated/numpy.arccos.html#numpy.arccos)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.arctan](https://numpy.org/doc/stable/reference/generated/numpy.arctan.html#numpy.arctan)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.arctan2](https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html#numpy.arctan2)
  - [ ] 1-D gh-47
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.hypot](https://numpy.org/doc/stable/reference/generated/numpy.hypot.html#numpy.hypot)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.sinh](https://numpy.org/doc/stable/reference/generated/numpy.sinh.html#numpy.sinh)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.cosh](https://numpy.org/doc/stable/reference/generated/numpy.cosh.html#numpy.cosh)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.tanh](https://numpy.org/doc/stable/reference/generated/numpy.tanh.html#numpy.tanh)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.arcsinh](https://numpy.org/doc/stable/reference/generated/numpy.arcsinh.html#numpy.arcsinh)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.arccosh](https://numpy.org/doc/stable/reference/generated/numpy.arccosh.html#numpy.arccosh)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.arctanh](https://numpy.org/doc/stable/reference/generated/numpy.arctanh.html#numpy.arctanh)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.degrees](https://numpy.org/doc/stable/reference/generated/numpy.degrees.html#numpy.degrees)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.radians](https://numpy.org/doc/stable/reference/generated/numpy.radians.html#numpy.radians)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.deg2rad](https://numpy.org/doc/stable/reference/generated/numpy.deg2rad.html#numpy.deg2rad)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.rad2deg](https://numpy.org/doc/stable/reference/generated/numpy.rad2deg.html#numpy.rad2deg)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.bitwise_and](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_and.html#numpy.bitwise_and)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.bitwise_or](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_or.html#numpy.bitwise_or)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.bitwise_xor](https://numpy.org/doc/stable/reference/generated/numpy.bitwise_xor.html#numpy.bitwise_xor)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.invert](https://numpy.org/doc/stable/reference/generated/numpy.invert.html#numpy.invert)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.left_shift](https://numpy.org/doc/stable/reference/generated/numpy.left_shift.html#numpy.left_shift)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.right_shift](https://numpy.org/doc/stable/reference/generated/numpy.right_shift.html#numpy.right_shift)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.greater](https://numpy.org/doc/stable/reference/generated/numpy.greater.html#numpy.greater)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.greater_equal](https://numpy.org/doc/stable/reference/generated/numpy.greater_equal.html#numpy.greater_equal)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.less](https://numpy.org/doc/stable/reference/generated/numpy.less.html#numpy.less)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.less_equal](https://numpy.org/doc/stable/reference/generated/numpy.less_equal.html#numpy.less_equal)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.not_equal](https://numpy.org/doc/stable/reference/generated/numpy.not_equal.html#numpy.not_equal)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.equal](https://numpy.org/doc/stable/reference/generated/numpy.equal.html#numpy.equal)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.logical_and](https://numpy.org/doc/stable/reference/generated/numpy.logical_and.html#numpy.logical_and)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.logical_or](https://numpy.org/doc/stable/reference/generated/numpy.logical_or.html#numpy.logical_or)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.logical_xor](https://numpy.org/doc/stable/reference/generated/numpy.logical_xor.html#numpy.logical_xor)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.logical_not](https://numpy.org/doc/stable/reference/generated/numpy.logical_not.html#numpy.logical_not)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.maximum](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html#numpy.maximum)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.minimum](https://numpy.org/doc/stable/reference/generated/numpy.minimum.html#numpy.minimum)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.fmax](https://numpy.org/doc/stable/reference/generated/numpy.fmax.html#numpy.fmax)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.fmin](https://numpy.org/doc/stable/reference/generated/numpy.fmin.html#numpy.fmin)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.isfinite](https://numpy.org/doc/stable/reference/generated/numpy.isfinite.html#numpy.isfinite)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.isinf](https://numpy.org/doc/stable/reference/generated/numpy.isinf.html#numpy.isinf)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.isnan](https://numpy.org/doc/stable/reference/generated/numpy.isnan.html#numpy.isnan)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.isnat](https://numpy.org/doc/stable/reference/generated/numpy.isnat.html#numpy.isnat)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.signbit](https://numpy.org/doc/stable/reference/generated/numpy.signbit.html#numpy.signbit)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.copysign](https://numpy.org/doc/stable/reference/generated/numpy.copysign.html#numpy.copysign)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.nextafter](https://numpy.org/doc/stable/reference/generated/numpy.nextafter.html#numpy.nextafter)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.spacing](https://numpy.org/doc/stable/reference/generated/numpy.spacing.html#numpy.spacing)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.modf](https://numpy.org/doc/stable/reference/generated/numpy.modf.html#numpy.modf)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.ldexp](https://numpy.org/doc/stable/reference/generated/numpy.ldexp.html#numpy.ldexp)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.frexp](https://numpy.org/doc/stable/reference/generated/numpy.frexp.html#numpy.frexp)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.floor](https://numpy.org/doc/stable/reference/generated/numpy.floor.html#numpy.floor)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.ceil](https://numpy.org/doc/stable/reference/generated/numpy.ceil.html#numpy.ceil)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D
- [ ] [numpy.trunc](https://numpy.org/doc/stable/reference/generated/numpy.trunc.html#numpy.trunc)
  - [ ] 1-D
  - [ ] 2-D
  - [ ] 3-D

**Comment by tylerjereddy** [comment]
The checklists don't include the supported types, but that would probably be too long anyway. We'll probably lean on parametrized testing for that.
